require("options.gruvbox")
require("options.lualine")
require("options.nvim-tree")
require("options.blankline")
require("options.treesitter")
require("options.viminspector")
require("options.completion")
require("options.lsp-diagnostics")
